//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_Car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araba
    {
        public int arabaId { get; set; }
        public string arabaMarka { get; set; }
        public string arabaModeli { get; set; }
        public string plaka { get; set; }
        public string arabaYakit { get; set; }
        public string arabaSanz { get; set; }
        public Nullable<int> kisiSay { get; set; }
        public Nullable<int> kapiSay { get; set; }
        public Nullable<int> bagaj { get; set; }
        public string klima { get; set; }
        public Nullable<int> fiyat { get; set; }
        public string gps { get; set; }
        public string foto { get; set; }
        public Nullable<int> kiralama { get; set; }
    }
}
