//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rent_a_Car.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carDatabaseEntities5 : DbContext
    {
        public carDatabaseEntities5()
            : base("name=carDatabaseEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Araba> Araba { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<Kiralama> Kiralama { get; set; }
        public virtual DbSet<Uye> Uye { get; set; }
    }
}
